# Generated by Django 5.0.4 on 2024-04-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('generic', 'Generic'), ('oracle', 'Oracle'), ('mysql', 'MySQL'), ('postgres', 'Postgres')], default='generic', max_length=20)),
                ('connection_str', models.CharField(max_length=300)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
