# Generated by Django 5.0.4 on 2024-06-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terno', '0003_table_pub_name_tablecolumn_pub_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcolumnselector',
            name='exclude_columns',
            field=models.ManyToManyField(blank=True, related_name='exclude_columns', to='terno.tablecolumn'),
        ),
        migrations.AddField(
            model_name='grouptableselector',
            name='exclude_tables',
            field=models.ManyToManyField(blank=True, related_name='exclude_tables', to='terno.table'),
        ),
        migrations.AlterField(
            model_name='groupcolumnselector',
            name='columns',
            field=models.ManyToManyField(blank=True, related_name='include_columns', to='terno.tablecolumn'),
        ),
        migrations.AlterField(
            model_name='grouptableselector',
            name='tables',
            field=models.ManyToManyField(blank=True, related_name='include_tables', to='terno.table'),
        ),
    ]
