# Generated by Django 5.0.4 on 2024-06-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terno', '0005_grouptablerowfilterselector'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='display_name',
            field=models.CharField(default='Datasource 1', max_length=20),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='connection_str',
            field=models.TextField(help_text='Connection string for the datasource', max_length=300),
        ),
    ]
