# Generated by Django 5.0.4 on 2024-06-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terno', '0006_datasource_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableselector',
            name='tables',
            field=models.ManyToManyField(blank=True, related_name='public_tables', to='terno.table'),
        ),
    ]
