# Generated by Django 5.0.4 on 2024-06-24 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terno', '0007_alter_tableselector_tables'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TableSelector',
            new_name='PrivateTableSelector',
        ),
    ]
