# Generated by Django 5.0.4 on 2024-06-24 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terno', '0008_rename_tableselector_privatetableselector'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableRowFilterSelector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_str', models.CharField(max_length=300)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terno.table')),
            ],
        ),
    ]
