# Generated by Django 5.0.4 on 2024-07-05 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terno', '0011_grouptablerowfilter_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TableRowFilterSelector',
            new_name='TableRowFilter',
        ),
    ]
