# Generated by Django 5.0.4 on 2024-07-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terno', '0016_alter_llmconfiguration_llm_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmconfiguration',
            name='api_key',
            field=models.CharField(help_text='Enter the API key for accessing the LLM service.', max_length=512),
        ),
        migrations.AlterField(
            model_name='llmconfiguration',
            name='llm_type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Gemini'), ('anthropic', 'Anthropic'), ('custom', 'CustomLLM')], help_text='Select the type of LLM (e.g., OpenAI, Gemini, etc.).', max_length=64),
        ),
        migrations.AlterField(
            model_name='llmconfiguration',
            name='model_name',
            field=models.CharField(blank=True, help_text='Specify the model name to use (leave blank for default).', max_length=256, null=True),
        ),
    ]
