# Generated by Django 5.0.4 on 2024-07-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terno', '0018_llmconfiguration_top_k'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmconfiguration',
            name='custom_parameters',
            field=models.JSONField(blank=True, help_text='Enter parameters as a JSON object. Use this field if you want to pass additional paramters than the one defined above. These parameters will be passed when invoking the LLM. Example: {"param1": "value1", "param2": "value2", ... and so on }. Note: Only include parameters that are supported by the LLM you are using, otherwise an error may occur.', null=True),
        ),
    ]
