# Generated by Django 5.0.4 on 2024-07-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terno', '0019_llmconfiguration_custom_parameters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='pub_name',
            new_name='public_name',
        ),
        migrations.RenameField(
            model_name='tablecolumn',
            old_name='pub_name',
            new_name='public_name',
        ),
        migrations.AddField(
            model_name='table',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='llmconfiguration',
            name='custom_parameters',
            field=models.JSONField(blank=True, help_text='Enter parameters as a JSON object. Use this field if you want to pass additional paramters than the one defined above. These parameters will be passed when invoking the LLM. Example: {"param1": value1, "param2": value2, ... and so on }. In case of string values, enclose it in either single or double quotes.Note: Only include parameters that are supported by the LLM you are using, otherwise an error may occur.', null=True),
        ),
    ]
