# Generated by Django 5.0.4 on 2024-07-23 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terno', '0020_rename_pub_name_table_public_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatetableselector',
            name='tables',
            field=models.ManyToManyField(blank=True, related_name='private_tables', to='terno.table'),
        ),
        migrations.CreateModel(
            name='PrivateColumnSelector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columns', models.ManyToManyField(blank=True, related_name='private_columns', to='terno.tablecolumn')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terno.datasource')),
            ],
        ),
    ]
