# Generated by Django 5.0.4 on 2024-07-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terno', '0021_alter_privatetableselector_tables_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmconfiguration',
            name='custom_parameters',
            field=models.JSONField(blank=True, help_text='Enter parameters as a JSON object. Use this field if you             want to pass additional paramters than the one defined above.             These parameters will be passed when invoking the LLM. Example: {"param1": value1, "param2": value2, ... and             so on }. In case of string values, enclose it in either             single or double quotes.Note: Only include parameters that are supported by the LLM             you are using, otherwise an error may occur.', null=True),
        ),
        migrations.AlterField(
            model_name='llmconfiguration',
            name='custom_system_message',
            field=models.TextField(blank=True, help_text='Optional system message to set the behavior             of the assistant (leave blank for default)', null=True),
        ),
        migrations.AlterField(
            model_name='llmconfiguration',
            name='max_tokens',
            field=models.IntegerField(blank=True, help_text='Specify the maximum number of tokens to             generate (leave blank for default).', null=True),
        ),
        migrations.AlterField(
            model_name='llmconfiguration',
            name='temperature',
            field=models.FloatField(blank=True, help_text='Set the sampling temperature where higher             values make output more random (leave blank for default).', null=True),
        ),
        migrations.AlterField(
            model_name='llmconfiguration',
            name='top_k',
            field=models.FloatField(blank=True, help_text='Set the top-k parameter value (Limits the model             to consider only the top k most probable next words).             Leave blank for default.', null=True),
        ),
        migrations.AlterField(
            model_name='llmconfiguration',
            name='top_p',
            field=models.FloatField(blank=True, help_text='Set the top-p sampling value (controls diversity             via nucleus sampling). Leave blank for default.', null=True),
        ),
    ]
