# Generated by Django 5.0.4 on 2024-08-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terno', '0026_promptlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='db_info',
            field=models.CharField(default='', max_length=50),
        ),
    ]
