# Generated by Django 5.0.4 on 2024-08-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terno', '0027_datasource_db_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='db_info',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
