# Generated by Django 5.0.4 on 2024-08-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terno', '0028_alter_datasource_db_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='db_info',
        ),
        migrations.AddField(
            model_name='datasource',
            name='dialect_name',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='dialect_version',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
