# Generated by Django 5.0.4 on 2024-09-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terno', '0030_systemprompts'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Give description of your datasource/schema.', max_length=1024, null=True),
        ),
    ]
