# Generated by Django 5.1.1 on 2024-09-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terno', '0031_datasource_connection_json_alter_datasource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='dialect_name',
            field=models.CharField(blank=True, default='', help_text='Auto-generated on save', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='dialect_version',
            field=models.CharField(blank=True, default='', help_text='Auto-generated on save', max_length=20, null=True),
        ),
    ]
