# Generated by Django 5.1.1 on 2024-09-20 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terno', '0031_datasource_description'),
        ('terno', '0032_alter_datasource_dialect_name_and_more'),
    ]

    operations = [
    ]
