# Generated by Django 5.1.1 on 2024-09-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terno', '0033_merge_20240920_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='dialect_name',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='dialect_version',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='llmconfiguration',
            name='custom_parameters',
            field=models.JSONField(blank=True, help_text='Enter parameters as a JSON object. Use this field if you             want to pass additional parameters than the one defined above.             These parameters will be passed when invoking the LLM. Example: {"param1": value1, "param2": value2, ... and             so on }. In case of string values, enclose it in either             single or double quotes.Note: Only include parameters that are supported by the LLM             you are using, otherwise an error may occur.', null=True),
        ),
    ]
