# Generated by Django 5.1.1 on 2024-09-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terno', '0034_alter_datasource_dialect_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmconfiguration',
            name='llm_type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Gemini'), ('anthropic', 'Anthropic'), ('ollama', 'Ollama'), ('custom', 'CustomLLM')], help_text='Select the type of LLM (e.g., OpenAI, Gemini, etc.).', max_length=64),
        ),
    ]
