# Generated by Django 5.1.1 on 2024-11-12 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terno', '0035_alter_llmconfiguration_llm_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constrained_columns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrained_columns', to='terno.tablecolumn')),
                ('referred_columns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_columns', to='terno.tablecolumn')),
                ('referred_schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='terno.datasource')),
                ('referred_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terno.table')),
            ],
        ),
    ]
