# Generated by Django 5.1.1 on 2024-11-12 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terno', '0036_foreignkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreignkey',
            name='constrained_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contrained_table', to='terno.table'),
        ),
        migrations.AlterField(
            model_name='foreignkey',
            name='referred_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_table', to='terno.table'),
        ),
    ]
