# Generated by Django 5.1.1 on 2024-11-08 09:11

from django.db import migrations
from django.core.management import call_command


def create_default_organisation(apps, schema_editor):
    Organisation = apps.get_model('terno', 'Organisation')
    OrganisationLLM = apps.get_model('terno', 'OrganisationLLM')
    OrganisationUser = apps.get_model('terno', 'OrganisationUser')
    OrganisationGroup = apps.get_model('terno', 'OrganisationGroup')
    OrganisationDataSource = apps.get_model('terno', 'OrganisationDataSource')
    User = apps.get_model('auth', 'User')
    LLMConfiguration = apps.get_model('terno', 'LLMConfiguration')
    DataSource = apps.get_model('terno', 'DataSource')
    Group = apps.get_model('auth', 'Group')

    call_command('createsuperuser', username="admin", email="admin@example.com", no_input=True)
    # Create default organisation
    user = User.objects.create(
        username='admin',
        email="admin@example.com",
        password="Superadmin@123",
        is_staff=True,
        is_superuser=True)
    print(user)

    default_org, created = Organisation.objects.get_or_create(
        name='Default Organisation',
        subdomain='',
        owner=User.objects.first(),
        is_active=True,
    )
    print('---------')
    print(User.objects.first())

    for llm in LLMConfiguration.objects.all():
        OrganisationLLM.objects.get_or_create(organisation=default_org, llm=llm)

    for datasource in DataSource.objects.all():
        OrganisationDataSource.objects.get_or_create(organisation=default_org, datasource=datasource)

    for user in User.objects.all():
        OrganisationUser.objects.get_or_create(organisation=default_org, user=user)

    for group in Group.objects.all():
        OrganisationGroup.objects.get_or_create(organisation=default_org, group=group)


class Migration(migrations.Migration):

    dependencies = [
        ('terno', '0036_organisation_organisationdatasource_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_organisation)
    ]
