# Generated by Django 5.1.1 on 2024-12-06 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terno', '0037_foreignkey_constrained_table_and_more'),
        ('terno', '0037_populate_default_org'),
    ]

    operations = [
    ]
