# Generated by Django 5.1.1 on 2024-12-11 09:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terno', '0038_merge_20241206_0845'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='organisationuser',
            constraint=models.UniqueConstraint(fields=('organisation', 'user'), name='user_organisation'),
        ),
    ]
