# Generated by Django 5.1.1 on 2025-01-29 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
        ('terno', '0039_organisationuser_user_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='llm_credit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.llmcredit'),
        ),
    ]
