# Generated by Django 5.1.1 on 2025-04-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terno', '0041_organisation_assign_llm_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='sample_rows',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tablecolumn',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tablecolumn',
            name='unique_categories',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
