# Generated by Django 5.1.1 on 2025-04-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terno', '0042_table_sample_rows_tablecolumn_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='description_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
