# Generated by Django 5.1.1 on 2025-04-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terno', '0043_table_description_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablecolumn',
            name='unique_categories',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
