# Generated by Django 5.1.1 on 2025-04-03 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terno', '0042_datasourcesuggestions'),
        ('terno', '0044_alter_tablecolumn_unique_categories'),
    ]

    operations = [
    ]
