# Generated by Django 5.1.1 on 2025-04-08 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terno', '0042_datasource_is_erp'),
        ('terno', '0045_merge_20250403_1133'),
    ]

    operations = [
    ]
