# Generated by Django 5.1.1 on 2025-04-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terno', '0045_merge_20250403_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='complete_description',
            field=models.BooleanField(default=False, help_text='Denotes if description is generated for the table and all its columns.'),
        ),
    ]
