# Generated by Django 5.1.1 on 2025-04-08 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terno', '0045_merge_20250403_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='dialect_name',
            field=models.CharField(blank=True, default='', help_text='Auto-generated on save', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='dialect_version',
            field=models.CharField(blank=True, default='', help_text='Auto-generated on save', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terno.organisation')),
            ],
        ),
    ]
