# Generated by Django 5.1.1 on 2025-04-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terno', '0046_merge_0042_datasource_is_erp_0045_merge_20250403_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='category',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
