# Generated by Django 5.1.1 on 2025-04-14 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terno', '0046_table_complete_description'),
        ('terno', '0047_table_category_alter_table_description'),
    ]

    operations = [
    ]
