# Generated by Django 5.1.1 on 2025-04-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terno', '0048_merge_20250414_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
