from django.shortcuts import render
from django.http import JsonResponse


def index(request):
    return render(request, 'frontend/index.html')


def generate_table_response(request):
    # convert the resultset generated by SQLAlchemy to JSON
    pass


def chat(request):
    return JsonResponse({'response': 'This is LLM response'})
