from django.shortcuts import render


def index(request):
    return render(request, 'sqlshield/index.html')

def generate_table_response(request):
    # convert the resultset generated by SQLAlchemy to JSON
    pass