name: Code Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.10-slim

    steps:
    - uses: actions/checkout@v4

    - name: Cache Apt Dependencies
      id: apt-cache
      uses: actions/cache@v3
      with:
        path: /var/cache/apt
        key: apt-cache-v1

    - name: Install Git and MySQL Dependencies
      if: steps.apt-cache.outputs.cache-hit != 'true'
      run: |
        apt-get update
        apt-get upgrade -y
        apt-get install -y gcc git default-libmysqlclient-dev libpq-dev pkg-config curl

    - name: Cache Python Dependencies
      id: pip-cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: pip-cache-v1-${{ hashFiles('requirements.txt') }}
      
    - name: Install Dependencies
      if: steps.pip-cache.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        coverage run terno/manage.py test terno && coverage report --fail-under=65 && coverage xml

    - name: Report to CodeCov
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}

      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        directory: ./coverage/reports/
        fail_ci_if_error: true
